[package]
name = "parse-sap-odata"
version = "1.2.3"
authors = ["Chris Whealy <chris@lighthouse.no>"]
edition = "2021"
description = "Generate Rust structs from SAP OData V2 metadata"
keywords = ["odata", "sap", "parser", "opendata"]
repository = "https://github.com/lighthouse-no/parse-sap-odata"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
rust_decimal = { version ="1", features = ["serde-with-str"]}

[dependencies]
anyhow = "1.0"
check_keyword = "0.2"
convert_case = "0.6"
quick-xml = { version = "0.30", features = ["serialize"] }
regex = "1.9"
serde = { version = "1.0", features = ["derive"] }
which = "4.0"
