use std::{collections::VecDeque, fmt::Formatter};

use crate::parser::generate::syntax_fragments::{
    CLOSE_PAREN, CLOSE_SQR, COLON, COMMA, END_BLOCK, LINE_FEED, NONE, OPEN_CURLY, OPEN_PAREN, OPEN_SQR, SOME,
};
use crate::{edmx::data_services::schema::association::Association, parser::generate::gen_owned_string};

static MY_NAME: &str = "Association";
static UNDERSCORE: &str = "_";

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Association[Set] names generated by SAP are always in the form "Assoc_<from_entity>_<to_entity>[_AssocSet]" up to a
// maximum length of 40 characters.  Names longer than 40 characters are simply truncated.

// Split an Association or AssociationSet name into its constituent parts and discard the "Assoc" prefix and as much of
// the "AssocSet" suffix as might be present.
pub fn normalise_assoc_name(assoc_name: &str) -> String {
    let mut assoc_name_parts = assoc_name.split(UNDERSCORE).collect::<VecDeque<&str>>();

    // Maybe remove the first element
    if assoc_name_parts[0].eq("Assoc") {
        let _ = assoc_name_parts.pop_front();
    };

    if "AssocSet".starts_with(assoc_name_parts[assoc_name_parts.len() - 1]) {
        let _ = assoc_name_parts.pop_back();
    };

    // Rebuild Association name using underscore as the separator
    assoc_name_parts
        .iter()
        .enumerate()
        .map(|(idx, name_part)| format!("{}{}", if idx == 0 { "" } else { UNDERSCORE }, name_part))
        .collect::<String>()
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
enum AssociationFieldNames {
    Name,
    SapContentVersion,
    Ends,
    ReferentialConstraint,
}

impl AssociationFieldNames {
    pub fn value(prop_name: AssociationFieldNames) -> &'static str {
        match prop_name {
            AssociationFieldNames::Name => "name",
            AssociationFieldNames::SapContentVersion => "sap_content_version",
            AssociationFieldNames::Ends => "ends",
            AssociationFieldNames::ReferentialConstraint => "referential_constraint",
        }
    }
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
fn line_into_association(f: &mut Formatter<'_>, prop_md: AssociationFieldNames, val: &str) -> std::fmt::Result {
    write!(f, "{}{}{}{}{}", AssociationFieldNames::value(prop_md), COLON, val, COMMA, LINE_FEED)
}

impl std::fmt::Display for Association {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        let ends_str = format!("{}{}{}{}{}", OPEN_SQR, self.ends[0], COMMA, self.ends[1], CLOSE_SQR);
        let ref_con_str;
        let ref_con = if let Some(rc) = &self.referential_constraint {
            ref_con_str = format!("{}{rc}{}", OPEN_PAREN, CLOSE_PAREN);
            [SOME, &ref_con_str].concat()
        } else {
            NONE.to_string()
        };

        write!(f, "{MY_NAME}")?;
        write!(f, "{OPEN_CURLY}")?;
        line_into_association(f, AssociationFieldNames::Name, &gen_owned_string(&self.name))?;
        line_into_association(f, AssociationFieldNames::SapContentVersion, &gen_owned_string(&self.sap_content_version))?;
        line_into_association(f, AssociationFieldNames::Ends, &ends_str)?;
        line_into_association(f, AssociationFieldNames::ReferentialConstraint, &ref_con)?;
        write!(f, "{END_BLOCK}")
    }
}
